"""Stack truth export — durable mq-stack gate snapshots for mqobsidian."""
from __future__ import annotations

import json
from datetime import UTC, datetime
from pathlib import Path
from typing import Any

DEFAULT_STACK_TRUTH_DIR = Path.home() / "mqobsidian" / "memory" / "stack-truth"


def _utc_now() -> datetime:
    return datetime.now(UTC)


def default_stack_truth_path(checked_at: str | None = None) -> Path:
    """Return the default dated mqobsidian stack-truth note path."""
    if checked_at:
        try:
            dt = datetime.fromisoformat(checked_at.replace("Z", "+00:00"))
        except ValueError:
            dt = _utc_now()
    else:
        dt = _utc_now()
    return DEFAULT_STACK_TRUTH_DIR / f"{dt.date().isoformat()}-mq-stack-truth.md"


def _load_gate_payload(raw: str | dict[str, Any]) -> dict[str, Any]:
    if isinstance(raw, dict):
        return raw
    return json.loads(raw)


def build_stack_truth_snapshot(
    contract_payload: str | dict[str, Any],
    release_payload: str | dict[str, Any],
) -> dict[str, Any]:
    """Combine contract-check and release-check payloads into one truth snapshot."""
    contract = _load_gate_payload(contract_payload)
    release = _load_gate_payload(release_payload)

    contract_ready = contract.get("overall") == "READY"
    release_ready = release.get("overall") == "GO"
    status = "READY" if contract_ready and release_ready else "NOT READY"

    contract_repos = {r.get("name"): r for r in contract.get("repos", [])}
    release_repos = {r.get("name"): r for r in release.get("repos", [])}
    names = sorted({n for n in set(contract_repos) | set(release_repos) if n})

    repos: list[dict[str, Any]] = []
    for name in names:
        c = contract_repos.get(name, {})
        r = release_repos.get(name, {})
        repos.append({
            "name": name,
            "version": r.get("version") or c.get("contract", {}).get("version") or "?",
            "contract_status": c.get("status", "UNKNOWN"),
            "contract_reason": c.get("reason", ""),
            "release_status": "GO" if r.get("go") else "NO-GO",
            "release_blockers": r.get("blockers", []),
            "release_warnings": r.get("warnings", []),
        })

    blockers: list[str] = []
    blockers.extend(contract.get("reasons", []))
    for repo in repos:
        for blocker in repo["release_blockers"]:
            blockers.append(f"{repo['name']}: {blocker}")

    warnings: list[str] = []
    for repo in repos:
        for warning in repo["release_warnings"]:
            warnings.append(f"{repo['name']}: {warning}")

    checked_at = contract.get("checked_at") or release.get("checked_at") or _utc_now().isoformat()
    return {
        "status": status,
        "checked_at": checked_at,
        "contract_overall": contract.get("overall"),
        "release_overall": release.get("overall"),
        "repos": repos,
        "blockers": blockers,
        "warnings": warnings,
    }


def render_stack_truth_markdown(snapshot: dict[str, Any]) -> str:
    """Render a stack truth snapshot as a durable Markdown note."""
    status = snapshot["status"]
    checked_at = snapshot["checked_at"]
    lines = [
        f"# MQ Stack Truth — {checked_at[:10]}",
        "",
        f"*Auto-generated by `mq-agent stack export` — {checked_at}*",
        "",
        "## Result",
        "",
        f"Status: **{status}**",
        f"Contract gate: `{snapshot.get('contract_overall', 'UNKNOWN')}`",
        f"Release gate: `{snapshot.get('release_overall', 'UNKNOWN')}`",
        "",
        "## Stack summary",
        "",
        "| Repo | Version | Contract | Release | Notes |",
        "|---|---:|---|---|---|",
    ]

    for repo in snapshot.get("repos", []):
        notes: list[str] = []
        if repo.get("contract_reason"):
            notes.append(repo["contract_reason"])
        notes.extend(repo.get("release_blockers", []))
        notes.extend(repo.get("release_warnings", []))
        note = "; ".join(notes) if notes else "—"
        lines.append(
            f"| {repo['name']} | {repo['version']} | {repo['contract_status']} | {repo['release_status']} | {note} |"
        )

    lines.extend(["", "## Blockers", ""])
    if snapshot.get("blockers"):
        for item in snapshot["blockers"]:
            lines.append(f"- {item}")
    else:
        lines.append("None.")

    lines.extend(["", "## Warnings", ""])
    if snapshot.get("warnings"):
        for item in snapshot["warnings"]:
            lines.append(f"- {item}")
    else:
        lines.append("None.")

    next_action = "Keep stack gates green."
    if status != "READY":
        next_action = "Fix blockers or drift, then rerun `mq-agent stack export`."

    lines.extend([
        "",
        "## Decisions",
        "",
        "- Stack truth is derived from contract-check plus release-check.",
        "- This note is a durable mqobsidian memory record, not a transient CI log.",
        "",
        "## Next action",
        "",
        next_action,
        "",
    ])
    return "\n".join(lines)


def stack_truth_export(output_path: str = "", write: bool = True) -> dict[str, Any]:
    """Collect gates, render Markdown, and optionally write to mqobsidian."""
    from mq_agent.tools.stack_tools import stack_contract_check, stack_release_check

    snapshot = build_stack_truth_snapshot(stack_contract_check(), stack_release_check())
    markdown = render_stack_truth_markdown(snapshot)
    dest = Path(output_path).expanduser() if output_path else default_stack_truth_path(snapshot["checked_at"])

    result = {
        "ok": snapshot["status"] == "READY",
        "status": snapshot["status"],
        "path": str(dest),
        "snapshot": snapshot,
        "markdown": markdown,
    }

    if write:
        dest.parent.mkdir(parents=True, exist_ok=True)
        dest.write_text(markdown, encoding="utf-8")
        result["written"] = True
    else:
        result["written"] = False

    return result
