"""Feedback engine contracts, runtime evidence and operator surfaces."""

from .candidates import (
    candidate_detail,
    list_candidates,
    maybe_create_candidate,
    memory_handoff,
    set_candidate_state,
)
from .contracts import (
    ACTIVATION_READINESS_SCHEMA_ID,
    CANDIDATE_SCHEMA_ID,
    COMPARISON_SCHEMA_ID,
    validate_activation_readiness,
    validate_candidate,
    validate_comparison,
)
from .engine import run_context_experiment
from .readiness import activation_readiness
from .evaluation import compare_feedback_run, latest_comparison, metric_pair
from .models import SCHEMA_ID, build_feedback_experiment, validate_experiment
from .store import (
    FeedbackHistoryResult,
    FeedbackReadResult,
    FeedbackStoreIssue,
    StoredFeedbackRecord,
    append_candidate,
    append_comparison,
    append_experiment,
    candidates_path,
    comparisons_path,
    experiments_path,
    feedback_root,
    purge_feedback_state,
    read_candidate_history,
    read_comparison_history,
    read_experiment_history,
    read_experiments,
    sanitize_feedback_record,
)
from .views import (
    REPORT_SCHEMA_ID,
    feedback_inspect,
    feedback_recent,
    feedback_report,
    feedback_status,
    validate_report,
)

__all__ = [
    "SCHEMA_ID",
    "REPORT_SCHEMA_ID",
    "COMPARISON_SCHEMA_ID",
    "CANDIDATE_SCHEMA_ID",
    "ACTIVATION_READINESS_SCHEMA_ID",
    "FeedbackHistoryResult",
    "FeedbackReadResult",
    "FeedbackStoreIssue",
    "StoredFeedbackRecord",
    "activation_readiness",
    "append_candidate",
    "append_comparison",
    "append_experiment",
    "build_feedback_experiment",
    "candidate_detail",
    "candidates_path",
    "compare_feedback_run",
    "comparisons_path",
    "experiments_path",
    "feedback_inspect",
    "feedback_recent",
    "feedback_report",
    "feedback_root",
    "feedback_status",
    "latest_comparison",
    "list_candidates",
    "maybe_create_candidate",
    "memory_handoff",
    "metric_pair",
    "purge_feedback_state",
    "read_candidate_history",
    "read_comparison_history",
    "read_experiment_history",
    "read_experiments",
    "run_context_experiment",
    "sanitize_feedback_record",
    "set_candidate_state",
    "validate_activation_readiness",
    "validate_candidate",
    "validate_comparison",
    "validate_experiment",
    "validate_report",
]
